# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector2 = np.zeros(10)
null_vector2
null_vector2[4] = 5
null_vector2

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector_1049 = np.array(range(10,50))
vector_1049

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector_1049[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
vector_3x3 = np.random.randint(0,9, size=(3,3))
vector_3x3

array([[8, 6, 1],
       [5, 7, 8],
       [0, 0, 1]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [14]:
L = [1,2,0,0,4,0]
l = []
for i in L:
    if i > 0:
        l.append(L.index(i))
print(l)
        

[0, 1, 4]


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [19]:
np.random.rand(3,3,3) 

array([[[0.29149211, 0.70717995, 0.77722429],
        [0.71842588, 0.60107314, 0.75354999],
        [0.81555524, 0.20882706, 0.4974795 ]],

       [[0.44264993, 0.73831854, 0.35533973],
        [0.1066996 , 0.07111291, 0.07698629],
        [0.73941238, 0.08608624, 0.15130491]],

       [[0.37127464, 0.15036278, 0.66318299],
        [0.88451267, 0.92165607, 0.38547402],
        [0.85757594, 0.83897238, 0.33407016]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
x = np.random.rand(10,10)
print(x)
print(f'max value is {np.max(x)}')
print(f'min value is {np.min(x)}')

[[9.45798322e-02 7.43262258e-01 1.57969052e-01 5.50969224e-01
  5.19892240e-01 8.77774875e-01 3.99099656e-01 4.80256762e-01
  6.74306278e-01 9.10753367e-01]
 [7.53371251e-01 9.66424499e-01 9.48908409e-04 6.38433569e-01
  3.99758643e-01 6.14086644e-01 6.38374966e-01 5.30121675e-03
  6.72534526e-01 4.62626325e-01]
 [3.00711011e-01 7.80044795e-01 3.14976833e-01 4.06146198e-01
  8.57744609e-01 8.01008170e-01 4.18976354e-01 3.33390774e-01
  3.29202372e-01 4.47910220e-01]
 [8.94595228e-01 5.53993208e-01 9.58700386e-01 8.46056767e-01
  7.61913947e-01 5.09029289e-01 4.93625483e-01 4.80048412e-01
  1.35559320e-01 9.27964746e-01]
 [3.75107760e-01 4.78837117e-01 1.86089009e-01 1.47438696e-01
  7.97060899e-01 2.51261622e-01 5.45919104e-02 8.24537538e-01
  1.51235886e-01 9.11059367e-01]
 [8.88002682e-01 3.37032918e-01 2.47759287e-01 3.04471394e-02
  4.87208805e-01 6.66371869e-02 5.45152817e-01 8.43391848e-01
  9.09379628e-01 3.57424334e-01]
 [9.21676595e-01 7.30992011e-01 6.35587214e-01 1.13199583e

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
y = np.random.random(30)
print(y)
print(f'Mean value is {np.mean(y)}')

[0.49128503 0.98789502 0.10628879 0.48740905 0.1745846  0.52211629
 0.18576833 0.5049209  0.73508165 0.50129036 0.07938251 0.53355237
 0.19993126 0.77020839 0.86794689 0.29967898 0.55900156 0.82490456
 0.80178964 0.1026722  0.70484522 0.85686877 0.25356303 0.9665881
 0.33789952 0.82232306 0.56936324 0.15460395 0.73508557 0.98676592]
Mean value is 0.5374538263621897


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
z = np.ones((5,5))
z
z[1:4,1:4] = np.zeros((3,3))
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [36]:
i = np.zeros((6,6))
i
i[1:5,1:5] = z
i

ValueError: could not broadcast input array from shape (5,5) into shape (4,4)

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [39]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 16. Normalize a 5x5 random matrix (★☆☆)

#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 18. How to round away from zero a float array ? (★☆☆)

#### 19. Find common values between two arrays? (★☆☆)

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 23. Create a random vector of size 10 and sort it (★★☆)

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 26. Find the closest value to random element in a vector? (★★☆)

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

#### 28. Sort an array by the nth column? (★★☆)

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 31. Swap two rows of an array? (★★★)

#### 32. How to negate a boolean value inside an array? (★★★)

#### 33. Find the most frequent value in an array?

#### 34. Get the n largest values of an array (★★★)

#### 35. Extract unique rows from a two dimensional array? (★★★)