Load in NumPy

In [5]:
import numpy as np

<b>The Basics</b>

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimension of numpy array
a.ndim

1

In [9]:
# Get Shgape
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int64')

In [11]:
# Get Size
a.itemsize

8

In [12]:
# Get total size
a.nbytes

24

<b>Accessing/Changing specific elements, rows, columns, etc</b>

In [13]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get  shape
a.shape

(2, 7)

In [15]:
# Get a specific element [r,  c]
a[1,5]

13

In [16]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [18]:
# Geting a little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [19]:
# Replace row element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [20]:
# Replace an entire column
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [21]:
#Replace entire column with multiple elements
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


<b>3D example</b>

In [22]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get specific element (work outside in)
b[0,1,1]

4

In [25]:
# replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [26]:
# replace
b[:,1,:] = [[9,9], [8,8]]

In [27]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

<b> Initializing Different Types of Arrays</b>

In [31]:
# All os matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [34]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [38]:
# any other number (full_like)
np.full_like(a, 4) #takes a pre existing shape 

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
# Matrix of Random decimal numbers
np.random.rand(4,2,3)

array([[[0.9842385 , 0.95926992, 0.55068623],
        [0.72993023, 0.48130334, 0.91217486]],

       [[0.16334274, 0.75207924, 0.48822527],
        [0.74803277, 0.48386035, 0.73777954]],

       [[0.49651679, 0.71253101, 0.67384854],
        [0.72071808, 0.18689482, 0.11631072]],

       [[0.86649798, 0.2292443 , 0.64973962],
        [0.61916195, 0.31111916, 0.17947624]]])

In [44]:
# Random Integer values
np.random.randint(4,7, size=(3,3)) # end number is exclusive

array([[5, 5, 4],
       [6, 5, 5],
       [5, 4, 5]])

In [46]:
# The Identity matrix is a square matrix by nature hence the single value addition
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# Repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0) # axis== 0 is rows axis==1 is columns
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
#Solution for grid layout
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


<b> Be careful when copying arrays!!!</b>

In [55]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(b)
print(a)
#both pointing at the same array

[100   2   3]
[100   2   3]


In [56]:
# correct way to copy array
a = np.array([1,2,3,])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


<b> Mathematics </b>

In [57]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [58]:
a + 2

array([3, 4, 5, 6])

In [59]:
a - 2

array([-1,  0,  1,  2])

In [60]:
a * 2

array([2, 4, 6, 8])

In [61]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [66]:
b = np.array([1,0,1,0])
a + b

array([6, 6, 8, 8])

In [67]:
a ** 2

array([25, 36, 49, 64])

In [68]:
# Take the sin of all the values
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [69]:
# Take the cos of all the values
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [70]:
# For a lot more (https://docs.scipy.org/doc/nupy/reference/routines.math.html)

##### Linear Algebra

In [75]:
# columns of the first matrix need to be equal to the rows of the second one.
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# Matrix multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [78]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# Reference docs (https://docs.scipy.org/doc/numpy/refernce/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Inverse
# Etc...

#### Statistics

In [79]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.min(stats, axis = 1)

array([1, 4])

In [81]:
np.max(stats)

6

In [82]:
np.sum(stats) # sums all the values in the matrix

21

In [83]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Reorganizing Arrays

In [86]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [88]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
# Horizontal Stack
h1 = np.ones((2,4,))
h2 = np.zeros((2,2,))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous
##### Load Data from File


In [91]:
np.genfromtxt('data.txt', delimiter=',')

FileNotFoundError: data.txt not found.